const plansData = [
    {
      plan: "Starter",
      price: 29,
      isHighlighted: false,
      planFeatures: [
        "Unlimited users",
        "Up to 2 teams",
        "Computer activity tracking",
        "Timesheet and attendance",
        "Custom rules to detect slacking employees",
        "Screenshots every 10 minutes",
        "Last 14 days data retention",
        "10 GB file storage limit",
      ],
    },
    {
      plan: "Pro",
      price: 42,
      isHighlighted: true,
      planFeatures: [
        "Unlimited tracking",
        "Unlimited teams",
        "Computer activity tracking",
        "Timesheet and attendance",
        "Custom rules to detect slacking employees",
        "Screenshots every 1 minute",
        "Last 1 year data retention",
        "Unlimited Storage",
        "Last 3 months screenshot retention",
        "Timelapse videos of work progress",
        "Data Export to CSV, XLS",
        "Priority support",
      ],
    },
    {
      plan: "Enterprise",
      price: null,
      isHighlighted: false,
      planFeatures: [
        "Unlimited tracking",
        "Unlimited teams",
        "Computer activity tracking",
        "Timesheet and attendance",
        "Custom rules to detect slacking employees",
        "Screenshots every 1 minute",
        "Last 1 year data retention",
        "Unlimited Storage",
        "Last 3 months screenshot retention",
      ],
    },
  ];
  export default plansData;